# prints port status using lsof
function busyport {
    lsof -n -i:$1 | grep LISTEN
}

# helps ídentity misterious IPs
function whosip {
    openssl s_client -showcerts -connect $1:$2 | grep CN
}

# golang's dep dependency graph (brew install graphviz)
function depgraph {
    dep status -dot | dot -T png | open -f -a /Applications/Preview.app
}
