export TERM=screen-256color
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/usr/local/opt/gnu-sed/libexec/gnubin:$HOME/go/bin:/usr/local/opt/fzf/bin

# go
export GOPATH=$HOME/go
export GOROOT=/usr/local/go

# use ctrl+o while fzf to open file in vim
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(vim {})+abort'"
