# load zsh debugger
# zmodload zsh/zprof

alias sudo="sudo " # allow to use aliases while sudoing
alias cat='bat' # cat with syntax highlightning
alias du="ncdu --color dark -rr --exclude .git --exclude node_modules" # disk usage
alias k='kubectl' # because kubectl is just way too long
alias la='eza -la --long --header --git' # ls -la for the day to day
alias ll='eza --long --header --git' # ls -la for the day to day
alias nan='tldr' # simplified man
alias path='echo $PATH | tr -s ":" "\n"' # dump path in a more clear way
alias ping='prettyping --nolegend' # ping for the 21st century
alias preview="fzf --preview 'bat --color \"always\" {}'" # preview files as you move through them
alias tls="tmux list-sessions" # list tmux sessions
alias top="htop" # top for the 21st century
alias d="date"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=5"

# load and bind edit-command-line to ctrl+space
autoload -Uz edit-command-line; zle -N edit-command-line
bindkey '^ ' edit-command-line

source ~/dotfiles/zsh/theme
source ~/dotfiles/zsh/fzf
source ~/dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# turn on autocompletion
# https://gist.github.com/ctechols/ca1035271ad134841284#gistcomment-2308206
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

[ -f ~/.profile ] && source ~/.profile

# dump debug info
# zprof

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
